version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_Ul2WzIZhNm1a
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: